var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};var titleHeader=document.querySelector(".title");function visibleTitle(){titleHeader.style.opacity="1"}
setTimeout(visibleTitle,500);var descHeader=document.querySelector(".desc");function visibleDesc(){descHeader.style.opacity="1"}setTimeout(visibleDesc,700);var burger=document.querySelector(".burger__icon"),menuUl=document.querySelector(".menu__ul"),closeBtn=document.querySelector(".close__btn"),MainMenu=document.querySelector(".main__menu"),linkMenu=document.querySelectorAll(".link__menu");
burger.addEventListener("click",function(){MainMenu.style.display="block";setTimeout(function(){menuUl.style.transform="translate(0)";MainMenu.style.zIndex="999"},700)});closeBtn.addEventListener("click",function(){menuUl.style.transform="translate(100vw)";setTimeout(function(){MainMenu.style.zIndex="";MainMenu.style.display=""},900)});
if(991>screen.width)for(var $jscomp$iter$0=$jscomp.makeIterator(linkMenu),$jscomp$key$linkM=$jscomp$iter$0.next();!$jscomp$key$linkM.done;$jscomp$key$linkM=$jscomp$iter$0.next())linkM=$jscomp$key$linkM.value,linkM.addEventListener("click",function(){menuUl.style.transform="translate(100vw)";setTimeout(function(){MainMenu.style.zIndex="";MainMenu.style.display=""},900)});
var swiper=new Swiper(".swiper",{direction:"horizontal",loop:!0,effect:"fade",fadeEffect:{crossFade:!0},autoplay:{delay:4E3}}),popupFirst=document.getElementById("popup__first"),btnSubmit=document.querySelector(".submit__btn"),formPopup=document.querySelector(".form__popup"),btnFirstPopup=document.querySelector(".first__popup"),formArea=document.querySelectorAll(".form__area"),validBlock=document.querySelector(".valid__form"),closeFirstPopup=document.querySelector(".close__form"),closeValid=document.querySelector(".close__valid");
btnFirstPopup.addEventListener("click",function(){popupFirst.style.display="block";setTimeout(function(){popupFirst.style.opacity="1"},700)});closeFirstPopup.addEventListener("click",function(){popupFirst.style.opacity="0";setTimeout(function(){popupFirst.style.display=""},700)});btnSubmit.addEventListener("click",function(){formPopup.style.display="none";setTimeout(function(){for(var a=$jscomp.makeIterator(formArea),b=a.next();!b.done;b=a.next())b.value.value=""},200);validBlock.style.display="flex"});
closeValid.addEventListener("click",function(){validBlock.style.opacity="0";setTimeout(function(){validBlock.style.display="";popupFirst.style.display="";popupFirst.style.opacity="";formPopup.style.display=""},700);setTimeout(function(){validBlock.style.opacity=""},700)});function Tabs(a){this.node=a.node;this.links=a.node.querySelectorAll(".tab-link");this.windows=a.node.querySelectorAll(".tab-window");this.activeIndex=0;this.initColled=!1;this.node.tabs=this;this.init()}
Tabs.prototype.init=function(){if(!this.initColled)for(var a=0;a<this.links.length;a++)this.link=this.links[a],this.handlerClick(this.link,a),this.windows[a].style.display="none",this.windows[0].style.display="block",this.links[0].classList.add("active")};Tabs.prototype.handlerClick=function(a,b){a.addEventListener("click",function(){this.goToTab(b)}.bind(this))};
Tabs.prototype.goToTab=function(a){a!==this.activeIndex&&0<=a&&a<=this.links.length&&(this.links[this.activeIndex].classList.remove("active"),this.links[a].classList.add("active"),this.windows[this.activeIndex].style.display="none",this.windows[a].style.display="block",this.activeIndex=a)};document.addEventListener("DOMContentLoaded",function(){var a=document.querySelector(".tabs");new Tabs({node:a})});
for(var thumbnails=document.getElementsByClassName("thumbnail"),overlay=document.getElementById("overlay"),overlayClose=document.getElementById("overlay-close"),overlayImage=document.getElementById("overlay-image"),i=0;i<thumbnails.length;i++)thumbnails[i].addEventListener("click",openOverlay);overlayClose.addEventListener("click",closeOverlay);overlay.addEventListener("keydown",overlay);overlayClose.addEventListener("click",closeOverlay);
function closeOverlay(a){27===a.keyCode&&overlay.classList.toggle("open")}function closeOverlay(a){overlay.classList.toggle("open")}function openOverlay(a){overlay.classList.toggle("open");overlayImage.src=a.target.src}
for(var prodElement=document.querySelectorAll(".prod"),btnLazy=document.querySelector(".lazy__btn"),$jscomp$loop$14={$jscomp$loop$prop$i$9$15:0};$jscomp$loop$14.$jscomp$loop$prop$i$9$15<prodElement.length;$jscomp$loop$14={$jscomp$loop$prop$i$9$15:$jscomp$loop$14.$jscomp$loop$prop$i$9$15},$jscomp$loop$14.$jscomp$loop$prop$i$9$15++)btnLazy.addEventListener("click",function(a){return function(){3<a.$jscomp$loop$prop$i$9$15&&8>a.$jscomp$loop$prop$i$9$15&&(setTimeout(function(){prodElement[a.$jscomp$loop$prop$i$9$15].style.opacity=
"1"},600),prodElement[a.$jscomp$loop$prop$i$9$15].style.display="")}}($jscomp$loop$14));for(var i$10=0;i$10<prodElement.length;i$10++)3<i$10&&8>i$10&&(prodElement[i$10].style.display="none",prodElement[i$10].style.opacity="0");
for(var $jscomp$loop$16={$jscomp$loop$prop$i$11$17:0};$jscomp$loop$16.$jscomp$loop$prop$i$11$17<prodElement.length;$jscomp$loop$16={$jscomp$loop$prop$i$11$17:$jscomp$loop$16.$jscomp$loop$prop$i$11$17},$jscomp$loop$16.$jscomp$loop$prop$i$11$17++)btnLazy.addEventListener("click",function(a){return function(){7<a.$jscomp$loop$prop$i$11$17&&500>a.$jscomp$loop$prop$i$11$17&&(setTimeout(function(){prodElement[a.$jscomp$loop$prop$i$11$17].style.opacity="1"},600),prodElement[a.$jscomp$loop$prop$i$11$17].style.display=
"")}}($jscomp$loop$16));for(var i$12=0;i$12<prodElement.length;i$12++)7<i$12&&500>i$12&&(prodElement[i$12].style.display="none",prodElement[i$12].style.opacity="0");
for(var wrappProdAll=document.querySelectorAll(".tab-window"),site=0,$jscomp$iter$2=$jscomp.makeIterator(wrappProdAll),$jscomp$key$wrappProd=$jscomp$iter$2.next();!$jscomp$key$wrappProd.done;$jscomp$key$wrappProd=$jscomp$iter$2.next()){var wrappProd=$jscomp$key$wrappProd.value;site=wrappProd.querySelectorAll(".prod").length;4<site?wrappProd.querySelector(".lazy__btn").style.display="":wrappProd.querySelector(".lazy__btn").style.display="none"}
for(var anchors=document.querySelectorAll("a.link__menu"),$jscomp$loop$18={},$jscomp$iter$3=$jscomp.makeIterator(anchors),$jscomp$key$anchor=$jscomp$iter$3.next();!$jscomp$key$anchor.done;$jscomp$loop$18={$jscomp$loop$prop$anchor$19:$jscomp$loop$18.$jscomp$loop$prop$anchor$19},$jscomp$key$anchor=$jscomp$iter$3.next())$jscomp$loop$18.$jscomp$loop$prop$anchor$19=$jscomp$key$anchor.value,$jscomp$loop$18.$jscomp$loop$prop$anchor$19.addEventListener("click",function(a){return function(b){b.preventDefault();
b=a.$jscomp$loop$prop$anchor$19.getAttribute("href");document.querySelector(b).scrollIntoView({behavior:"smooth",block:"start"})}}($jscomp$loop$18));
for(var btnProd=document.querySelectorAll(".btn__prod"),prodElementAll=document.querySelectorAll(".prod"),namesProd=document.querySelector(".names__prod"),cenaProd=document.querySelector(".cena__prod"),sizeFormActual=document.querySelector(".size__form"),inputFormProd=document.querySelectorAll(".form__prod"),submitBtnProd=document.querySelector(".submit__btn-prod"),formPopupProd=document.querySelector(".form__popup-prod"),popupProduct=document.getElementById("popup__product"),validFormProd=document.querySelector(".valid__form-prod"),
closeValidProd=document.querySelector(".close__valid-prod"),$jscomp$iter$5=$jscomp.makeIterator(btnProd),$jscomp$key$btnProdAll=$jscomp$iter$5.next();!$jscomp$key$btnProdAll.done;$jscomp$key$btnProdAll=$jscomp$iter$5.next()){var btnProdAll=$jscomp$key$btnProdAll.value;btnProdAll.addEventListener("click",function(){for(var a=$jscomp.makeIterator(prodElementAll),b=a.next();!b.done;b=a.next())prodElAll=b.value,namesProd.value=prodElAll.querySelector(".prod__name").textContent.trim(),cenaProd.value=prodElAll.querySelector(".cena").textContent.trim(),
sizeFormActual.innerHTML=prodElAll.querySelector(".size").textContent;setTimeout(function(){popupProduct.style.opacity="1"},600);popupProduct.style.display="block"})}var closeFormProd=document.querySelector(".close__form-prod");
closeFormProd.addEventListener("click",function(){namesProd.value="";cenaProd.value="";sizeFormActual.innerHTML="";for(var a=$jscomp.makeIterator(inputFormProd),b=a.next();!b.done;b=a.next())b.value.value="";setTimeout(function(){popupProduct.style.display=""},600);popupProduct.style.opacity=""});
submitBtnProd.addEventListener("click",function(){formPopupProd.style.display="none";setTimeout(function(){namesProd.value="";cenaProd.value="";sizeFormActual.innerHTML="";for(var a=$jscomp.makeIterator(inputFormProd),b=a.next();!b.done;b=a.next())inputFprod=b.value,inputFprod.value=""},600);validFormProd.style.display="flex"});
closeValidProd.addEventListener("click",function(){validFormProd.style.display="none";setTimeout(function(){popupProduct.style.display="";formPopupProd.style.display=""},600);popupProduct.style.opacity=""});
for(var overlayWindow=document.querySelector(".overlay"),overlayWindowClose=document.querySelector(".close__overlay"),prodImg=document.querySelectorAll(".prod__img"),prodImgItem=document.querySelectorAll(".prod__img img"),overlayWrapp=document.querySelector(".overlay__wrapp"),$jscomp$loop$20={},$jscomp$iter$8=$jscomp.makeIterator(prodImg),$jscomp$key$prodImgOpen=$jscomp$iter$8.next();!$jscomp$key$prodImgOpen.done;$jscomp$loop$20={$jscomp$loop$prop$prodImgOpen$21:$jscomp$loop$20.$jscomp$loop$prop$prodImgOpen$21},
$jscomp$key$prodImgOpen=$jscomp$iter$8.next())$jscomp$loop$20.$jscomp$loop$prop$prodImgOpen$21=$jscomp$key$prodImgOpen.value,$jscomp$loop$20.$jscomp$loop$prop$prodImgOpen$21.addEventListener("click",function(a){return function(){overlayWindow.style.display="block";var b=a.$jscomp$loop$prop$prodImgOpen$21.cloneNode(!0);overlayWrapp.appendChild(b);setTimeout(function(){overlayWindow.style.opacity="1"},800)}}($jscomp$loop$20));
overlayWindowClose.addEventListener("click",function(){overlayWindow.style.opacity="0";setTimeout(function(){overlayWindow.style.display=""},800);document.querySelector(".overlay__wrapp .prod__img").remove()});
